# Generated by Django 4.0.1 on 2022-01-27 11:27

import autoslug.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('POSTAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Postlar'},
        ),
        migrations.AddField(
            model_name='postmodel',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 11, 27, 16, 972230, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='Draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='PostImages'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='ModifiedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 11, 27, 19, 421122, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='Slug',
            field=autoslug.fields.AutoSlugField(default=datetime.datetime(2022, 1, 27, 11, 27, 20, 837193, tzinfo=utc), editable=False, max_length=150, populate_from='Title', unique=True),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='postmodel',
            table='Posts',
        ),
    ]
