# Generated by Django 4.0.1 on 2022-01-28 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSTAPP', '0003_commentmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ('CreatedDate',), 'verbose_name': 'Yorum', 'verbose_name_plural': 'Yorumlar'},
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='Parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='POSTAPP.commentmodel'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='POSTAPP.postmodel', verbose_name='Post'),
        ),
    ]
