# Generated by Django 4.0.1 on 2022-01-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSTAPP', '0004_alter_commentmodel_options_commentmodel_parent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentModel',
        ),
    ]
