# Generated by Django 4.0.1 on 2022-02-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSTAPP', '0006_alter_postmodel_options_likesdislikes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likesdislikes',
            options={'verbose_name': 'Beğeni', 'verbose_name_plural': 'Beğeniler'},
        ),
        migrations.AlterModelTable(
            name='likesdislikes',
            table='LikesDislikes',
        ),
    ]
