# Generated by Django 4.0.1 on 2022-02-05 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSTAPP', '0008_rename_likesdislikes_likesdislikesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesdislikesmodel',
            name='isLike',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
    ]
