# Generated by Django 4.0.1 on 2022-02-05 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSTAPP', '0009_alter_likesdislikesmodel_islike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikesDislikesModel',
        ),
    ]
