# Generated by Django 4.0.2 on 2022-02-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSTAPP', '0010_delete_likesdislikesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='PostImages'),
        ),
    ]
