# Generated by Django 4.0.1 on 2022-02-05 18:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('POSTAPP', '0010_delete_likesdislikesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesDislikesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isLike', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_and_dislikes', to='POSTAPP.postmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beğeni',
                'verbose_name_plural': 'Beğeniler',
                'db_table': 'LikesDislikes',
            },
        ),
    ]
