# Generated by Django 4.0.1 on 2022-02-05 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIKESAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likesdislikesmodel',
            name='isLike',
        ),
    ]
