# Generated by Django 4.0.1 on 2022-02-05 19:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSTAPP', '0010_delete_likesdislikesmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LIKESAPP', '0002_remove_likesdislikesmodel_islike'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikesDislikesModel',
            new_name='PostLikesDislikesModel',
        ),
    ]
