# Generated by Django 4.0.1 on 2022-02-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIKESAPP', '0003_rename_likesdislikesmodel_postlikesdislikesmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postlikesdislikesmodel',
            table='PostLikesDislikes',
        ),
    ]
