# Generated by Django 4.0.1 on 2022-02-05 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSTAPP', '0010_delete_likesdislikesmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LIKESAPP', '0004_alter_postlikesdislikesmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLikesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='POSTAPP.postmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Beğeni',
                'verbose_name_plural': 'Post Beğenileri',
                'db_table': 'PostLikes',
            },
        ),
        migrations.DeleteModel(
            name='PostLikesDislikesModel',
        ),
    ]
