# Generated by Django 4.0.1 on 2022-01-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0002_alter_profilemodel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={},
        ),
        migrations.AlterModelTable(
            name='profilemodel',
            table=None,
        ),
    ]
