# Generated by Django 4.0.1 on 2022-01-31 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0003_alter_profilemodel_options_alter_profilemodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profil'},
        ),
        migrations.AlterModelTable(
            name='profilemodel',
            table='Profile',
        ),
    ]
