# Generated by Django 4.0.1 on 2022-01-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAVORITES', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritesmodel',
            options={'verbose_name': 'Favori', 'verbose_name_plural': 'Favoriler'},
        ),
        migrations.AlterModelTable(
            name='favoritesmodel',
            table='Favorites',
        ),
    ]
